### ISSUE TITLE
Replacement of symbolic links is no longer working

### ISSUE THREAD

**Issue by ufroehling** [unclebob/fitnesse#610] opened 2015-02-04 09:17 UTC
I have a symbolic link with name=XyTeam and path=.MyApp/XyTeam/TrunK. Now i try to replace it i by entering the existing name and the new desired path = .MyApp/XyTeam/ReL11 and click on the Create/Replace button. I then get the error message "...  already has a child named XyTeam ". 

Version is the latest from 20150114.
In our live version 20131110 the replacement is still possible and used regularly.

**Comment by mwarhaftig** [comment] 2015-02-18 02:05
Hi Ufroehling, thanks for the detailed info on the bug, was able to recreate and will look into the cause.

**Comment by mwarhaftig** [comment] 2015-02-18 05:18
Commit b47bea tightened the Symbolic Link behavior but also introduced the bug you encountered.  Submitted pull request to resolve.

**Comment by mwarhaftig** [comment] 2015-02-18 13:19
Did a little more research and don't think b47bea introduced the issue. Most likely it was later changes to FileSystemPageFactory.createSymbolicPage (bug only started happening with release 20140630). The fix remains the same.

**Comment by amolenaar** [comment] 2015-02-23 22:16
fixed by Matt

**Closed by amolenaar** 2015-02-23 22:16 UTC
