### ISSUE TITLE
Pretty-printed exception messages broken in 20191229

### ISSUE THREAD

**Issue by fhoeben** [unclebob/fitnesse#1252] opened 2020-01-07 11:15 UTC
In version 20191229 pretty-printed exceptions returned by Slim (the message starts with `message:<<` and ends with `>>`) are no longer handled correctly.
If the message-content (between the `<<` and `>>`) ends with one or more `>` these are stripped from the contents before it is passed to the HTML display.

This can break existing fixture that pass exception messages containing HTML tags (for instance to include screen shots or links in the HTML test report). See https://github.com/fhoeben/hsac-fitnesse-fixtures/issues/294

**Comment by fhoeben** [comment] 2020-01-07 11:32
@six42 Can you elaborate why you introduced the behaviour that part of the message may be ignored (by making the regex non-greedy)?

(On a side note: as you marked the wiki test you created as unit test, would it not be better to add those checks to the jUnit test `SlimExceptionResultTest`, so all the class' until tests are in one place?)

**Comment by fhoeben** [comment] 2020-01-07 16:29
I believe the following test shows the problem:
```
  @Test
  public void messageWithHtmlContent() {
    SlimExceptionResult result = new SlimExceptionResult("key", "message:<<<div>Bad things<br/><span>happened</span></div>>>");
    assertTrue(result.hasMessage());
    assertEquals("<div>Bad things<br/><span>happened</span></div>", result.getMessage());
  }
```

I

**Comment by six42** [comment] 2020-01-07 19:09
If you have nested exceptions:  Exception with message caused by another Exception with message  the greedy regex would return both messages with the stack trace in between. 

In your example an extra space before the closing >> should  workaround the problem.
Also not helpful for existing code
Changing the regex to look for white after the >> should work.

**Comment by six42** [comment] 2020-01-07 23:24
Thanks for the additional test. I send a PR
your pattern makes a different case fail in FitNesse.SuiteAcceptanceTests.SuiteSlimTests.TestExceptionIsDisplayed.SlimExceptionResult

Regarding your side note.
I think we should drink our own champagne and use FitNesse to test FirNesse and not Junit where possible.
If you are OK I add the drop of the JUnit test to the PR as all scenarios are covered in the Wiki page.

**Comment by fhoeben** [comment] 2020-01-08 06:49
Thanks for the quick follow up.

I like making sure my code works so it should be tested. Using the most appropriate tool makes things easier. For a test such as this, which I consider quite low level a real unit test, I would prefer to use jUnit and use FitNesse for integration tests. But they both work and you have created the setup so that adding this extra test case is quite a simple and elegant change. So I'm also happy with the wiki test.

**Closed** 2020-01-08 07:08 UTC
