### ISSUE TITLE
Why is text underlined?

### ISSUE THREAD

**Issue by pvbemmelen62** [unclebob/fitnesse#1381] opened 2022-08-15 12:10 UTC
Some text in a wiki page is shown underlined when the mouse moves over it, for no apparent reason.

1. Go to http://fitnesse.org/FitNesse.UserGuide
2. Move mouse over text of the Introduction section
3. Observe that the first part of the text gets underlined when the mouse is over it.

I would expect that only hyperlinks are shown underlined when the mouse is over it; not normal text.

http://fitnesse.org/FitNesse.UserGuide :
![image](https://user-images.githubusercontent.com/11163367/184631639-b173ca25-1c7e-4cc9-90ec-1292b51bc52e.png)

Part of the text in the editor ( http://localhost:9090/FitNesse.UserGuide?edit) :
![image](https://user-images.githubusercontent.com/11163367/184631887-eff9e5c1-ad2d-4ce6-a42b-650a352da451.png)

My goal is to write documentation for Fitnesse test scripts and test software in the Fitnesse wiki environment.
That way no MS Word or Confluence, or other tool is needed; and the documentation is in the same location as the Fitnesse test scripts.

**Comment by fhoeben** [comment] 2022-08-15 13:30
The problem is caused by the fact that the supplied wiki content turns the whole first part of the introduction paragraph (util the link to `http://fitnesse.org/FitNesse.UserGuide.AcceptanceTests`) into content for a second `a` tag created for `!anchor introduction`, instead of creating just a single `a` tag without content inside the `h2` tag.

A simple workaround, I believe, is just to move the the `!anchor introduction` to the line above the `!1 Introduction`. But we should fix the parser to generate proper HTML when the anchor is inside a header

<img width="561" alt="Screenshot 2022-08-15 at 15 25 06" src="https://user-images.githubusercontent.com/5467859/184644530-969215b1-8792-4e17-831d-508941e13e02.png">

**Comment by fhoeben** [comment] 2022-08-15 13:49
This is so weird. I had the problem locally, I changed the headings to have the anchors above them, the problem went away. No I revert my changes and the problem still does not re-appear, no more strange extra `a` tags that I do see in production...

What's up?

**Comment by fhoeben** [comment] 2022-08-15 15:36
I believe the issue with the incorrect generated `<a>` is already fixed in the current master branch...

**Comment by fhoeben** [comment] 2022-08-15 16:19
Problem fixed on http://fitnesse.org/FitNesse.UserGuide and in release 20220815

**Closed by fhoeben** 2022-08-15 16:19 UTC
Labels: Bug
