### ISSUE TITLE
Caching issues: Most recent changes to pages seem to be gone if I edit a page again

### ISSUE THREAD

**Issue by ALuckyGuy** [unclebob/fitnesse#819] opened 2015-10-13 19:20 UTC
Downloaded the standalone.jar from Oct 10th, 2015 and am now noticing when I make page changes, if I immediately go back and edit the page, the changes appear to be gone. If I check the disk, the changes are in fact saved to contents.txt. I can "Edit", click Cancel to close the page, click Edit again and the changes don't show up, even if I do so multiple times. Eventually the page changes are correctly shown but I'm not sure if it's only due to the passage of time or something else.

Thought maybe it was browser related but I've reproduced the same issue multiple times in both the latest Chrome and FireFox releases.  Prior to this I was running the Aug 14th release which does not have this problem.

**Comment by ALuckyGuy** [comment] 2015-10-13 19:25
Also noticed this with changing symbolic links. Sometimes the page refreshes after clicking "Create Link" and the link does not show up. Re-opening the properites page and again, still gone, though the sym link works ok in practice. Wait a while and go back to the properties page - suddenly it shows up. This problem with new SymLinks "disappearing" isn't occurring as frequently as regular edits and might be related to another issue I'm in the process of documenting

**Comment by amolenaar** [comment] 2015-10-16 09:35
I check the first issue you reported, but can't reproduce it (Chrome 46.0.2490.71 on OS X 10.11). Edit, save and Edit again opens the edit page with the content I last saved.

You might want to check if the network is actually hit, by opening the developer toolbar and check the network traffic. Is the page actually reloaded or fetched from cache?

**Comment by ALuckyGuy** [comment] 2015-10-16 21:07
Hmm... very puzzling. I'm not able to reproduce it today and I can't figure out what might have changed. The fact that it was happening in both Chrome and FireFox means it wasn't really a browser problem, but I didn't restart the server either so why today is it suddenly working??  I hit it repeatedly yesterday.

If I notice the problem again I'll post back.

**Comment by amolenaar** [comment] 2015-11-08 21:25
Can we close this, as it is not reproducible?

**Comment by ALuckyGuy** [comment] 2015-11-08 22:43
Yes, I believe so. Thanks.

**Closed** 2015-11-09 10:52 UTC
