### ISSUE TITLE
Official JAVA 17 (LTS) support 

### ISSUE THREAD

**Issue by HoneyBadgerSeeker** [unclebob/fitnesse#1338] opened 2021-10-08 14:42 UTC
**Is your feature request related to a problem? Please describe.**
No, not for now, it seems working fine with Java 17.

**Describe the solution you'd like**
The new LTS version of Java is available ([Java 17](https://www.oracle.com/news/announcement/oracle-releases-java-17-2021-09-14/)). 
FitNesse should be officially compatible with it.

The [FitNesse download page](http://fitnesse.org/FitNesseDownload), state that 
> Ensure you have a supported Java version installed (either version 8 or 11, **versions >= 15 are not supported**).

**Comment by enexusde** [comment] 2022-05-11 08:46
Using RestFixtures a 

Could not complete testing: java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release

Exception is thrown.

**Comment by fhoeben** [comment] 2022-05-11 10:02
@enexusde is the exception thrown from RestFixture code (if so you should probably file the issue at https://github.com/smartrics/RestFixture), or from FitNesse itself?

If the error comes from FitNesse, can you provide a stack trace where the exception is thrown and preferably a reproduction path using the only code present in this project?

**Comment by tcnh** [comment] 2022-05-13 11:55
I've seen that same exception, but only with a Java 18 JRE. That's where it was removed from the runtime.

**Comment by enexusde** [comment] 2022-07-11 17:35
@fhoeben From FitNesse

**Comment by lehtmets** [comment] 2023-04-04 22:13
I saw this waring with Java 17 (17.0.6 temurin)
`
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by fitnesse.slim.instructions.SystemExitSecurityManager (file:/Users/ml/.gradle/caches/modules-2/files-2.1/org.fitnesse/fitnesse/20221102/b5ce9b528912742591c26c6893e8e091aeed543a/fitnesse-20221102.jar)
WARNING: Please consider reporting this to the maintainers of fitnesse.slim.instructions.SystemExitSecurityManager
WARNING: System::setSecurityManager will be removed in a future release
`

**Comment by Voyinno** [comment] 2023-12-21 16:48
#1455

**Comment by unexist** [comment] 2024-07-31 13:37
I stumbled upon this due to the exact error messages. This is fixed int he recent version, as can be seen in the Changelog:

https://github.com/unclebob/fitnesse/releases/tag/20240707

And the matching PR:

https://github.com/unclebob/fitnesse/pull/1513

**Closed** 2024-08-08 10:23 UTC
Labels: Feature Request
