### ISSUE TITLE
HTML content is always included in XML result file

### ISSUE THREAD

**Issue by ufroehling** [unclebob/fitnesse#771] opened 2015-07-21 09:15 UTC
In the past it was optional to have the HTML content tags included in the XML results to keep them compact. See http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.AdministeringFitNesse.RestfulServices.RestfulSuiteXmlFormat
And we have the REST parameter &includeHTML for the ?suite command to include them on demand. 
But at least in our currently used version v20150424 the HTML content tag is always included which blows up the result files. See the comment for the includeHtml parameter: "If format=xml then this will cause the XML to contain a 'content' tag that holds the HTML of the tested page. Beware, this can lead to OutOfMemory errors for large suites."
My colleagues and I want the old behaviour back

Can be reproduced with 
http://localhost:8090/FitNesse.SuiteAcceptanceTests.SuiteSlimTests.QueryTableSuite?suite&format=xml

**Comment by mwarhaftig** [comment] 2015-07-26 04:04
Hi ufroehling, looks like you found a bug - the behavior you want should have not been removed.  Details on the cause and fix are on the associated merge request.

**Comment by amolenaar** [comment] 2015-07-27 14:09
Merged :)

**Closed by amolenaar** 2015-07-27 14:09 UTC
