### ISSUE TITLE
Could not invoke constructor for MapFixture[0] or The instance scriptTableActor.setValueFor. does not exist

### ISSUE THREAD

**Issue by Mrle1992** [unclebob/fitnesse#1444] opened 2023-08-22 13:33 UTC
I have a problem, when I run a test in the fitness program, it gives me this Could not invoke constructor for MapFixture[0] for some function and The instance scriptTableActor.setValueFor for another. does not exist. It also gives me this error ookie "latestContext" does not have a proper "SameSite" attribute value. Soon, cookies without the "SameSite" attribute or with an invalid value will be treated as "Lax". This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the "SameSite=None" attribute to it. To know more about the "SameSite" attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite ExampleSuite.Environment.Acceptance.TestScripts.DesktopDevice.ScopeInsight:27:39
![Untitled999](https://github.com/unclebob/fitnesse/assets/142903765/4e3edbd8-14e5-4804-9b80-44e67b0e9fea)

**Comment by fhoeben** [comment] 2023-08-23 15:58
Duplicate of https://github.com/fhoeben/hsac-fitnesse-fixtures/issues/528

**Closed by fhoeben** 2023-08-23 15:58 UTC
