### ISSUE TITLE
Is it possible to call an internal method when Stop Test button is pressed?

### ISSUE THREAD

**Issue by Semard** [unclebob/fitnesse#961] opened 2016-08-17 11:29 UTC
Hi,

We have an external program TTG, which we want to stop end the Stop Test button is pressed.

Usually this is done at the end of each suite but when the stop test button is pressed, this is not excuted.
    @Override
    public boolean endTestSuite(){
        entering(Thread.currentThread().getStackTrace()[1].getMethodName());
        setTtg(TTGFixture.getInstance());
        ttg.stopTTG();
        logger.finer("TTGFixture stopped!");
        boolean res = true;
        res = removeAllSUTs();
        exiting(Thread.currentThread().getStackTrace()[1].getMethodName());
        return res;
    }  

We tried to write a new class, packaging it into a TestResponder.jar-file and placing it together with the fitnesse_standalone-jar file:
package saft.top.top_main;

public class TestResponder {

```
public TestResponder() {
    super();
    // TODO Auto-generated constructor stub
}
```

}

and adding a plugins.properties file:
Responders=stoptest:saft.top.top_main.TestResponder

This did not work and an Error message was given SEVERE: Error while starting the FitNesse [Unable to load class...

How can this be solved? It seems it should be something that is something that should always be done... Taking down the system in an orderly manner even if the Stop Test button is pressed.

Best Regards
Joergen, Software Tester/Integration & Test Tool Developer

**Comment by six42** [comment] 2016-08-21 13:37
Hi Joergen,

Use the JVM Runtime.getRuntime().addShutdownHook
to make sure your fixture gets terminated in all cases.
Add this to the same JVM instance which calls your endTestSuite() function.

Kind Regards
Six42

**Comment by Semard** [comment] 2016-08-24 10:34
Hi Six42,

Thank you for the reply, it seems very promising! We have tried the solution as follows.

In our main-class:
---------------------------
    public void attachShutDownHook(){
        Runtime.getRuntime().addShutdownHook(new Thread() {
            @Override
            public void run() {
                System.out.println("Inside Add Shutdown Hook");
                endTestSuite();
            }
        });
        System.out.println("Shut Down Hook Attached.");
    }
---------------------------
.
.
.
In the same main-class we have the start test case method:

     *******************************************************
     ** Methods related to starting/stopping suites and
     ** single test cases.
     *******************************************************
     */
    @Override
    public boolean startTestCase(String testName){
        entering(Thread.currentThread().getStackTrace()[1].getMethodName());

        attachShutDownHook();
        System.out.println("Last instruction of Program....");
        
        exiting(Thread.currentThread().getStackTrace()[1].getMethodName());
        return res;
    }
---------------------------

However the endTestSuite(); method does not seem to be executed, when the stop button is pressed.

Have we implemented the solution correct? Any suggestions on how we can preceed?

Best Regards
 Joergen, Software Tester/Integration & Test Tool Developer

**Comment by six42** [comment] 2016-08-26 06:55
Hallo Joergen,
I would need some more information.
Can you send the output of the Execution Log.
and the Wiki page which triggers the calls of the startTestCase method.

**Comment by Semard** [comment] 2016-09-06 14:16
Hi,
This is the log, code and wikipages:

Part of execution log:
13:13:52 : BaseFixture.startTest.entering
13:13:52 INFO: Logging stopped at: 2016-09-06 13:13:52
Shut Down Hook Attached.
Last instruction of Program....
13:13:52 INFO: 
13:13:52 INFO: Test case: CheckScResponseTime
13:13:52 DEBUG: Start the testcase= CheckScResponseTime_2016_09_06_131352
13:13:52 DEBUG: OutputCaptureMode = enable
13:13:52 ********************************************************************************
13:13:52 2016-09-06 - Running test case: CheckScResponseTime
13:13:52 ********************************************************************************

…
13:13:56 INFO: SC_response_time=10000
13:13:56 INFO: SC response time is fullfilled for message : HFF_EXI_Ctrl_Transceive
13:13:56 DEBUG: com.gxa.saft.sc.evaluation.CheckSCResponseTime.CheckResponseTimeToBeLessThanMicrosecondsWithThresholdMicroseconds.EXITING
13:13:56 DEBUG: Selected message: SP_EXI_Ctrl
13:13:56 : **************************************
13:13:56 :  Check Response Time ...
13:13:56 : **************************************
13:13:56 DE


Code:

@Override
    public boolean startTestCase(String testName){
        entering(Thread.currentThread().getStackTrace()[1].getMethodName());
        attachShutDownHook();
        System.out.println("Last instruction of Program....");
        if(BaseFixture.abandonSuite && (settings.get("AbandonSuiteActive")==null ||settings.get("AbandonSuiteActive").equalsIgnoreCase("ON"))){
            abandonTestCase();
            return false;
        }

        ………
   }

    public void attachShutDownHook(){
        Runtime.getRuntime().addShutdownHook(new Thread() {
            @Override
            public void run() {
                System.out.println("Inside Add Shutdown Hook");
                endTestSuite();
            }
        });
        System.out.println("Shut Down Hook Attached.");
    }

Wiki page:
|com.saft.top.top_main.Message|
!|start test|${RUNNING_PAGE_NAME}|
!|add to test specification|${RUNNING_PAGE_PATH}.${RUNNING_PAGE_NAME}|test case|${RUNNING_PAGE_NAME}|

The log seems to be interrupted rather promtly and the shutdownhook is never called. Almost as if the stop button is in another JVM process. The shutdownhook and  endTestSuite() and startTestCase is all in the same class(Message.java). Just for test purposes we added a system.exit() in startTestCase directly after attachShutDownHook();. In that case the shutdownhook was indeed called but not executed in full(i.e. the printout inside hook was executed but not the call to end test suite).

Best Regards
Joergen, Software Tester/Integration & Test Tool Developer

**Comment by six42** [comment] 2016-09-14 19:45
Hi Joergen,

Your code is correct.
The problem is in Java itself : http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8056139
If you can move to Linux it should work.
If this is not an option than the question would be why you need to stop a running test?
If we understand your use case there might be another workaround.

**Comment by Semard** [comment] 2016-10-04 12:09
Hi,
Thank you! 
That helped a lot, feels good to know that it actually is related to a bug. 

The use-case was that the tester during development had some time consuming test cases/suites. During these development/sit-by-and-watch test sessions it happened that the test broke or was  erraneos in some way and the tester wanted to stop the test or in some cases the suite. Which in turn led to that we had no possibility to gracefulle shut down all the surrounding test tools that our java process used.

Moving to Linux is not an option at present, but certainly something worth taking into consideration in the future.

We have now taken another approach. When the surrounding testtools have an alivecheck message that is not acknowledged by our javaprocess(i.e. thread), they now take down themselves gracefully and closes all sockets, datareading streams and so on.

Best Regards
Joergen, Software Tester/Integration & Test Tool Developer

**Comment by amolenaar** [comment] 2016-11-29 07:54
It may be an option to start other threads explicitly as daemon threads, so they do not prevent the JVM from shutting down.

I'll close this issue as there's nothing to do from our end.

**Closed by amolenaar** 2016-11-29 07:54 UTC
