### ISSUE TITLE
Enhancement: change SLIM protocol format to use JSON

### ISSUE THREAD

**Issue by Kosta-Github** [unclebob/fitnesse#565] opened 2014-12-04 08:34 UTC
What do you think about the idea of replacing the proprietary SLIM protocol format by using JSON instead?

Was already mentioned here: https://github.com/unclebob/fitnesse/pull/189#issuecomment-20883024 and in #290

**Comment by six42** [comment] 2015-01-25 01:07
Hi Kosta,

Could you describe with an example which problem the protocol change would solve?
In principal it is easy to change the protocol (just two classes to change, also in every slim implementation). 
But in the wiki server you enter, see and compare text strings.  This is the hard part to change: To allow  any kind of JSON object to be entered, displayed and compared.
Custom comparators can do part of this already.

**Comment by adrianshum** [comment] 2015-01-28 03:45
Help to get rid of limitation of 999,999 characters for string and list maybe?

**Comment by six42** [comment] 2015-01-28 12:28
That limitation is gone. Only limit is your pc memory now :-)

**Comment by Kosta-Github** [comment] 2015-01-28 19:51
While it is possible to implement the SLIM protocol on the client side (the test executor side) on your own (I did that for C++ for example: https://github.com/Kosta-Github/fitnesse-cppslim), using an existing standard just like JSON would make it easier jump starting using Fitnesse on additional languages/technologies just like Python, JavaScript, node.js, and so on.

**Comment by amolenaar** [comment] 2015-12-27 19:27
Duplicate of #290?

**Closed by amolenaar** 2015-12-27 19:27 UTC
Labels: slim2
