### ISSUE TITLE
Version 20190224 does not display test results properly in Internet Explorer 11

### ISSUE THREAD

**Issue by Rhialto74** [unclebob/fitnesse#1196] opened 2019-03-20 19:45 UTC
I recently updated our Fitnesse install to the 20190224 and it seems our test results do not display properly in Internet Explorer 11, while they do in Chrome. I can navigate to the pages fine, but if I run a test they fail in IE and go to the generic not found error page.

I downgraded to 20190202 and that works fine.

When I traced the issue it appears that the request data being returned to IE in the later version does not contain the closing `</footer>`, `</body>` and `</html>` tags.

**Comment by fhoeben** [comment] 2019-03-20 21:58
Very strange indeed. @tcnh, do you think this might have something to do with #1189? 
I don't see how that would work (maybe because now `closeChunks()` is called before `closeTrailer()`?), but...

**Comment by tcnh** [comment] 2019-03-21 09:48
I'm looking in to it, but can't figure it out just yet. The mentioned change doesn't skip any html, just a CRLF.
What I can see is that the closing tags for footer, body and html are sent in the output bytestream. I'll install a VM with IE11 tonight to try and reproduce.

@Rhialto74 You say you're redirected to the notFound responder? If the output were incomplete I'd expect an empty page in IE11..

**Comment by Rhialto74** [comment] 2019-03-21 11:56
The last response I get is a 200 from Fitnesse and then it displays the
default ”Internet Explorer cannot display the webpage” error page.

FYI, I wasn’t the only one that reproed this particular issue, as I
initially tested in Chrome which works, it was only after I uploaded the
updated JAR file to our repository and a colleague tried it in IE that it
was found. I reproed it after that.

It’s definitely working properly in 20190202.

**Comment by tcnh** [comment] 2019-03-22 09:41
I am able to reproduce and can confirm the problem disappears when closeTrailer is called twice. What happens if we don't call it twice, the response ends with `0 CRLF`, if we don't it ends with ` CRLF`. The first one breaks IE11.

Changing the order of actions in ChunkedResponse.close() from `closeChunks -> closeTrailer -> sender.close` to `closeTrailer -> closeChunks -> sender.close` resolves the issue, but I can not test if that also prevents the exception in debian-based OS-es from #1187 right now.

**Closed** 2019-04-05 20:41 UTC
