### ISSUE TITLE
Recently, there was a false statement that troubled me，pageHistory ？

### ISSUE THREAD

**Issue by cmaster007** [unclebob/fitnesse#1440] opened 2023-08-06 08:39 UTC
D:\fitnesse\fitnesse20190119>java -jar -Xms42678M -Xmx42678M -Xmn8024M -Xss8024K -XX:MaxMetaspaceSize=8024m  -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=D:\dump fitnesse-standalone.jar  -a password.txt -p 8010 -f plugins.properties
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
Loaded custom comparator inverse: fitnesse.slim.test.InverseComparator
Bootstrapping FitNesse, the fully integrated standalone wiki and acceptance testing framework.
root page: fitnesse.wiki.fs.FileSystemPage at .\FitNesseRoot#latest
logger: none
authenticator: fitnesse.authentication.MultiUserAuthenticator
page factory: fitnesse.html.template.PageFactory
page theme: bootstrap
Starting FitNesse on port: 8010
Test system terminated with exception [Invocation of method 'getDateString' in  class fitnesse.reporting.history.SuiteExecutionReport threw exception java.lang.NullPointerException at suiteXML.vm[line 5, column 31]]
Test system terminated with exception [fitnesse.testsystems.TestExecutionException: fitnesse.testsystems.slim.SlimCommunicationException: Could not send/receive data with SUT]
Test system terminated with exception [fitnesse.testsystems.TestExecutionException: fitnesse.testsystems.slim.SlimCommunicationException: Could not send/receive data with SUT]
Test system terminated with exception [fitnesse.testsystems.TestExecutionException: fitnesse.testsystems.slim.SlimCommunicationException: Could not send/receive data with SUT]
Test system terminated with exception [fitnesse.testsystems.TestExecutionException: fitnesse.testsystems.slim.SlimCommunicationException: Could not send/receive data with SUT]
Test system terminated with exception [fitnesse.testsystems.TestExecutionException: fitnesse.testsystems.slim.SlimCommunicationException: Could not send/receive data with SUT]
Test system terminated with exception [fitnesse.testsystems.TestExecutionException: fitnesse.testsystems.slim.SlimCommunicationException: Could not send/receive data with SUT]
Test system terminated with exception [fitnesse.testsystems.TestExecutionException: fitnesse.testsystems.slim.SlimCommunicationException: Could not send/receive data with SUT]
Test system terminated with exception [fitnesse.testsystems.TestExecutionException: fitnesse.testsystems.slim.SlimCommunicationException: Could not send/receive data with SUT]
Test system terminated with exception [fitnesse.testsystems.TestExecutionException: fitnesse.testsystems.slim.SlimCommunicationException: Could not send/receive data with SUT]
Test system terminated with exception [IO Error rendering template 'suiteXML.vm']
WARNING: Socket Exception at: 1691278815475 [Software caused connection abort: socket write error]
java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
        at fitnesse.FitNesseExpediter.send(FitNesseExpediter.java:64)
        at fitnesse.http.ChunkedResponse.closeChunks(ChunkedResponse.java:80)
        at fitnesse.http.ChunkedResponse.addTrailingHeader(ChunkedResponse.java:70)
        at fitnesse.responders.run.SuiteResponder.closeHtmlResponse(SuiteResponder.java:392)
        at fitnesse.responders.run.SuiteResponder.doSending(SuiteResponder.java:132)
        at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:74)
        at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:29)
        at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:87)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:53)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Test system terminated with exception [IO Error rendering template 'suiteXML.vm']
WARNING: Socket Exception at: 1691281838015 [Software caused connection abort: socket write error]
java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
        at fitnesse.FitNesseExpediter.send(FitNesseExpediter.java:64)
        at fitnesse.http.ChunkedResponse.closeChunks(ChunkedResponse.java:80)
        at fitnesse.http.ChunkedResponse.addTrailingHeader(ChunkedResponse.java:70)
        at fitnesse.responders.run.SuiteResponder.closeHtmlResponse(SuiteResponder.java:392)
        at fitnesse.responders.run.SuiteResponder.doSending(SuiteResponder.java:132)
        at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:74)
        at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:29)
        at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:87)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:53)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Test system terminated with exception [IO Error rendering template 'suiteXML.vm']
WARNING: Socket Exception at: 1691281849765 [Software caused connection abort: socket write error]
java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
        at fitnesse.FitNesseExpediter.send(FitNesseExpediter.java:64)
        at fitnesse.http.ChunkedResponse.closeChunks(ChunkedResponse.java:80)
        at fitnesse.http.ChunkedResponse.addTrailingHeader(ChunkedResponse.java:70)
        at fitnesse.responders.run.SuiteResponder.closeHtmlResponse(SuiteResponder.java:392)
        at fitnesse.responders.run.SuiteResponder.doSending(SuiteResponder.java:132)
        at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:74)
        at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:29)
        at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:87)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:53)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Test system terminated with exception [IO Error rendering template 'suiteXML.vm']
WARNING: Socket Exception at: 1691281877093 [Software caused connection abort: socket write error]
java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
        at fitnesse.FitNesseExpediter.send(FitNesseExpediter.java:64)
        at fitnesse.http.ChunkedResponse.closeChunks(ChunkedResponse.java:80)
        at fitnesse.http.ChunkedResponse.addTrailingHeader(ChunkedResponse.java:70)
        at fitnesse.responders.run.SuiteResponder.closeHtmlResponse(SuiteResponder.java:392)
        at fitnesse.responders.run.SuiteResponder.doSending(SuiteResponder.java:132)
        at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:74)
        at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:29)
        at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:87)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:53)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Test system terminated with exception [IO Error rendering template 'suiteXML.vm']
WARNING: Socket Exception at: 1691281896811 [Software caused connection abort: socket write error]
java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
        at fitnesse.FitNesseExpediter.send(FitNesseExpediter.java:64)
        at fitnesse.http.ChunkedResponse.closeChunks(ChunkedResponse.java:80)
        at fitnesse.http.ChunkedResponse.addTrailingHeader(ChunkedResponse.java:70)
        at fitnesse.responders.run.SuiteResponder.closeHtmlResponse(SuiteResponder.java:392)
        at fitnesse.responders.run.SuiteResponder.doSending(SuiteResponder.java:132)
        at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:74)
        at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:29)
        at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:87)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:53)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Test system terminated with exception [IO Error rendering template 'testResults.vm']
WARNING: Socket Exception at: 1691282204747 [Software caused connection abort: socket write error]
java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
        at fitnesse.FitNesseExpediter.send(FitNesseExpediter.java:64)
        at fitnesse.http.ChunkedResponse.closeChunks(ChunkedResponse.java:80)
        at fitnesse.http.ChunkedResponse.addTrailingHeader(ChunkedResponse.java:70)
        at fitnesse.responders.run.SuiteResponder.closeHtmlResponse(SuiteResponder.java:392)
        at fitnesse.responders.run.SuiteResponder.doSending(SuiteResponder.java:132)
        at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:74)
        at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:29)
        at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:87)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:53)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Test system terminated with exception [IO Error rendering template 'testResults.vm']
WARNING: Socket Exception at: 1691282225685 [Software caused connection abort: socket write error]
java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
        at fitnesse.FitNesseExpediter.send(FitNesseExpediter.java:64)
        at fitnesse.http.ChunkedResponse.closeChunks(ChunkedResponse.java:80)
        at fitnesse.http.ChunkedResponse.addTrailingHeader(ChunkedResponse.java:70)
        at fitnesse.responders.run.SuiteResponder.closeHtmlResponse(SuiteResponder.java:392)
        at fitnesse.responders.run.SuiteResponder.doSending(SuiteResponder.java:132)
        at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:74)
        at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:29)
        at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:87)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:53)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Test system terminated with exception [IO Error rendering template 'testResults.vm']
WARNING: Socket Exception at: 1691282234451 [Software caused connection abort: socket write error]
java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
        at fitnesse.FitNesseExpediter.send(FitNesseExpediter.java:64)
        at fitnesse.http.ChunkedResponse.closeChunks(ChunkedResponse.java:80)
        at fitnesse.http.ChunkedResponse.addTrailingHeader(ChunkedResponse.java:70)
        at fitnesse.responders.run.SuiteResponder.closeHtmlResponse(SuiteResponder.java:392)
        at fitnesse.responders.run.SuiteResponder.doSending(SuiteResponder.java:132)
        at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:74)
        at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:29)
        at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:87)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:53)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Test system terminated with exception [IO Error rendering template 'testResults.vm']
WARNING: Socket Exception at: 1691282243108 [Software caused connection abort: socket write error]
java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
        at fitnesse.FitNesseExpediter.send(FitNesseExpediter.java:64)
        at fitnesse.http.ChunkedResponse.closeChunks(ChunkedResponse.java:80)
        at fitnesse.http.ChunkedResponse.addTrailingHeader(ChunkedResponse.java:70)
        at fitnesse.responders.run.SuiteResponder.closeHtmlResponse(SuiteResponder.java:392)
        at fitnesse.responders.run.SuiteResponder.doSending(SuiteResponder.java:132)
        at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:74)
        at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:29)
        at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:87)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:53)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Test system terminated with exception [IO Error rendering template 'suiteXML.vm']
WARNING: Socket Exception at: 1691284561719 [Software caused connection abort: socket write error]
java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
        at fitnesse.FitNesseExpediter.send(FitNesseExpediter.java:64)
        at fitnesse.http.ChunkedResponse.closeChunks(ChunkedResponse.java:80)
        at fitnesse.http.ChunkedResponse.addTrailingHeader(ChunkedResponse.java:70)
        at fitnesse.responders.run.SuiteResponder.closeHtmlResponse(SuiteResponder.java:392)
        at fitnesse.responders.run.SuiteResponder.doSending(SuiteResponder.java:132)
        at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:74)
        at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:29)
        at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:87)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:53)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Test system terminated with exception [IO Error rendering template 'suiteXML.vm']
WARNING: Socket Exception at: 1691285064701 [Software caused connection abort: socket write error]
java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
        at fitnesse.FitNesseExpediter.send(FitNesseExpediter.java:64)
        at fitnesse.http.ChunkedResponse.closeChunks(ChunkedResponse.java:80)
        at fitnesse.http.ChunkedResponse.addTrailingHeader(ChunkedResponse.java:70)
        at fitnesse.responders.run.SuiteResponder.closeHtmlResponse(SuiteResponder.java:392)
        at fitnesse.responders.run.SuiteResponder.doSending(SuiteResponder.java:132)
        at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:74)
        at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:29)
        at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:87)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:53)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Test system terminated with exception [IO Error rendering template 'suiteXML.vm']
WARNING: Socket Exception at: 1691285197450 [Software caused connection abort: socket write error]
java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
        at fitnesse.FitNesseExpediter.send(FitNesseExpediter.java:64)
        at fitnesse.http.ChunkedResponse.closeChunks(ChunkedResponse.java:80)
        at fitnesse.http.ChunkedResponse.addTrailingHeader(ChunkedResponse.java:70)
        at fitnesse.responders.run.SuiteResponder.closeHtmlResponse(SuiteResponder.java:392)
        at fitnesse.responders.run.SuiteResponder.doSending(SuiteResponder.java:132)
        at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:74)
        at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:29)
        at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:87)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:53)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Test system terminated with exception [IO Error rendering template 'suiteXML.vm']
WARNING: Socket Exception at: 1691285863333 [Software caused connection abort: socket write error]
java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
        at fitnesse.FitNesseExpediter.send(FitNesseExpediter.java:64)
        at fitnesse.http.ChunkedResponse.closeChunks(ChunkedResponse.java:80)
        at fitnesse.http.ChunkedResponse.addTrailingHeader(ChunkedResponse.java:70)
        at fitnesse.responders.run.SuiteResponder.closeHtmlResponse(SuiteResponder.java:392)
        at fitnesse.responders.run.SuiteResponder.doSending(SuiteResponder.java:132)
        at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:74)
        at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:29)
        at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:87)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:53)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Test system terminated with exception [IO Error rendering template 'suiteXML.vm']
WARNING: Socket Exception at: 1691285902212 [Software caused connection abort: socket write error]
java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
        at fitnesse.FitNesseExpediter.send(FitNesseExpediter.java:64)
        at fitnesse.http.ChunkedResponse.closeChunks(ChunkedResponse.java:80)
        at fitnesse.http.ChunkedResponse.addTrailingHeader(ChunkedResponse.java:70)
        at fitnesse.responders.run.SuiteResponder.closeHtmlResponse(SuiteResponder.java:392)
        at fitnesse.responders.run.SuiteResponder.doSending(SuiteResponder.java:132)
        at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:74)
        at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:29)
        at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:87)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:53)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Test system terminated with exception [IO Error rendering template 'suiteXML.vm']
WARNING: Socket Exception at: 1691309234808 [Software caused connection abort: socket write error]
java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
        at fitnesse.FitNesseExpediter.send(FitNesseExpediter.java:64)
        at fitnesse.http.ChunkedResponse.closeChunks(ChunkedResponse.java:80)
        at fitnesse.http.ChunkedResponse.addTrailingHeader(ChunkedResponse.java:70)
        at fitnesse.responders.run.SuiteResponder.closeHtmlResponse(SuiteResponder.java:392)
        at fitnesse.responders.run.SuiteResponder.doSending(SuiteResponder.java:132)
        at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:74)
        at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:29)
        at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:87)
        at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:53)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by cmaster007** [comment] 2023-08-06 08:41
I call fitnesse with the fitnesse plugin of jenkins

**Comment by fhoeben** [comment] 2023-08-08 11:13
Which Java version are you using, and which OS (it seems some version of Windows)?

The command/stack trace don't seem to be from a Jenkins run, are they?

The subject of this issue doesn't seem to match the stack trace. Can you share what the wiki contents of the suite is. A way we could reproduce the issue?

**Comment by cmaster007** [comment] 2023-08-09 08:52
hello,  


  java  version  1.8    server:  window  server 2016 


Sometimes the xml file generated is relatively large, reaching 2G. How can xml be generated in jenkins without the plug-in?


















At 2023-08-08 19:13:11, "Fried Hoeben" ***@***.***> wrote:

Which Java version are you using, and which OS (it seems some version of Windows)?

The command/stack trace don't seem to be from a Jenkins run, are they?

The subject of this issue doesn't seem to match the stack trace. Can you share what the wiki contents of the suite is. A way we could reproduce the issue?

**Comment by fhoeben** [comment] 2023-08-09 17:00
What exactly do you need the XML for. When you use the jUnit runner you'll get 'surefire XML' files generated, one for each test I believe. Jenkins picks these up automatically and parses them to report passed and failed tests. Is that what you need?

**Comment by cmaster007** [comment] 2023-08-16 06:57
hello
      I have a coredump file here, can you analyze it, I send you
















At 2023-08-10 01:00:40, "Fried Hoeben" ***@***.***> wrote:

What exactly do you need the XML for. When you use the jUnit runner you'll get 'surefire XML' files generated, one for each test I believe. Jenkins picks these up automatically and parses them to report passed and failed tests. Is that what you need?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

从网易163邮箱发来的超大附件推荐客户端极速下载
heapdump-1692105698875.hprof (1.63G, 2023年8月31日 14:47 到期)
下载
threaddump-1692105152732.tdump (18.63K, 2023年8月31日 14:47 到期)
下载
threaddump-1692105363553.tdump (18.62K, 2023年8月31日 14:47 到期)
下载

**Comment by fhoeben** [comment] 2024-02-19 06:30
I believe the error in XML generation was caused by an error during test system startup, which FitNesse failed to handle/log properly in its results.

Error handling should be improved in release 20240219.

I'm going to close this issue, since it provides not insight into the actual underlying problem. Feel free to create a new one if you are still experiencing issues (which are caused by FitNesse)

**Closed by fhoeben** 2024-02-19 06:30 UTC
Labels: Bug
